# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip3 install -e .[dev,test,alldns]

      # run tests!  Most config is in pyprojects.toml rather than --options since 0.8.4
      - run:
          name: run tests
          command: |
            make testdata
            find . -type f -name *.pyc -delete | echo
            coverage erase
            coverage run && ln -s tests/coverage/.coverage .coverage && bash <(curl -s https://codecov.io/bash)

      - run:
          name: run tests reports
          command: |      
            coverage report --fail-under=85

      - run:
          name: run static analyzers
          command: |
            black --check . ||  { printf "\\n\\t please use black to format your code."; exit 77; }
            pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y sewer/

      - run:
          name: run sewer cli
          command: |
            sewer --version && sewer --help

      # run make upload

      - store_artifacts:
          path: test-reports
          destination: test-reports
